### ISSUE TITLE
🐛 [bug] - Cosmetic - Hyperlinks pointing to incorrect/different endpoints 

### ISSUE THREAD

**Issue by avinashsingh77** [opendatahub-io-contrib/data-mesh-pattern#63]
### 📝 Description

The following URLs as mentioned in https://github.com/opendatahub-io-contrib/data-mesh-pattern#data-mesh-pattern are pointing to incorrect endpoints:
[How to Move Beyond a Monolithic Data Lake to a Distributed Data Mesh](_https://opendatahub.io/_) -- Zhamak Dehghani, Thoughtworks

[Data Mesh Principles and Logical Architecture](_https://old.ceph.com/ceph-storage/object-storage/_) -- Zhamak Dehghani, Thoughtworks

 
### 🚶 Steps to reproduce
Click on any of the following two URLs in https://github.com/opendatahub-io-contrib/data-mesh-pattern#data-mesh-pattern:
[How to Move Beyond a Monolithic Data Lake to a Distributed Data Mesh](https://opendatahub.io/) -- Zhamak Dehghani, Thoughtworks

[Data Mesh Principles and Logical Architecture](https://old.ceph.com/ceph-storage/object-storage/) -- Zhamak Dehghani, Thoughtworks

### 🧙‍♀️ Suggested solution
[How to Move Beyond a Monolithic Data Lake to a Distributed Data Mesh] should(most probably) be linked to https://martinfowler.com/articles/data-monolith-to-mesh.html

[Data Mesh Principles and Logical Architecture] should(most probably) be linked to https://martinfowler.com/articles/data-mesh-principles.html

**Comment by avinashsingh77** [comment]
Hey @caldeirav , I can work on this issue.

**Comment by caldeirav** [comment]
Sure feel free to go ahead and correct this
