### ISSUE TITLE
Notebook image for Data Mesh is not working

### ISSUE THREAD

**Issue by caldeirav** [opendatahub-io-contrib/data-mesh-pattern#84]
The custom notebook image for Data Mesh is not being started successfully from the RHODS console:

![Image](https://github.com/opendatahub-io-contrib/data-mesh-pattern/assets/23565280/b528a81f-c81b-4acd-a701-1e62eed0bc0e)

![Image](https://github.com/opendatahub-io-contrib/data-mesh-pattern/assets/23565280/d198e8c2-c5ef-4701-aa02-23bf34bc4d70)

There are issues with the image build.

**Comment by avinashsingh77** [comment]
Saw this error in workbook pod:
```
[E 2023-09-04 07:04:18,118.118] Error loading schemas for SchemasProvider 'code-snippets' - Descriptors cannot not be created directly.If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0.If you cannot immediately regenerate your protos, some other possible workarounds are: 1. Downgrade the protobuf package to 3.20.x or lower. 2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).
```

Added the following to `supply-chain/elyra/datamesh/Dockerfile` as a workaround
```
RUN /opt/app-root/bin/pip3 install protobuf==3.20.0 && \
    export PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python
```
Managed to launch the workbench with datamesh image

Awaiting permanent resolution and will then implement the same

**Comment by avinashsingh77** [comment]
Got this from ODH team - 
`you may just keep the protobuf downgrade to 3.20.x and leave env var PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION to not impact the performance`
Removed the line which was setting `PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION` from https://gitlab-ce.apps.cluster-djbb6.djbb6.sandbox2519.opentlc.com/rainforest/data-mesh-pattern/-/blob/main/supply-chain/elyra/datamesh/Dockerfile

**Comment by avinashsingh77** [comment]
As tested by @caldeirav , server is now starts okay with custom datamesh image
